artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/SreeDharsiniDevaraj/newRepo1/raw/refs/heads/main/books_data.zip
  dataset_dir: dataset # save the csv file
  ingested_dir: ingested_data
  raw_data_dir: raw_data # download the zip file